apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test
  labels:
    app: api-test
  namespace: cdp-recruitment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-test
  template:
    metadata:
      labels:
        app: api-test
    spec:
      containers:
        - name: api-test
          image: tiflo/api-test
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: api-test
  labels:
    app: api-test
  namespace: cdp-recruitment
spec:
  selector:
    app: api-test
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort